import { Generator } from '@idleberg/yeoman-generator';
import { languages } from '@nsis/language-data';
import { pascalCase } from 'change-case';
import { inverse } from 'kleur/colors';
import $ from '../../package.json' with { type: 'json' };

export default class extends Generator {
	constructor(args, opts) {
		super(args, opts);

		this.option('store-strings', { desc: 'Store translated language strings for next time', default: false });

		this.storeStrings = this.options.looseVersion;
	}

	languageChoices() {
		return Object.entries(languages)
			.map(([key, value]) => ({
				label: value.long || key,
				value: key,
			}))
			.sort((a, b) => a.label.localeCompare(b.label));
	}

	async prompting() {
		console.log(/* let it breathe */);

		this.clack.intro(inverse(` ${$.name} `));

		const answers = await this.prompt([
			{
				type: 'text',
				name: 'name',
				message: "What's the name of the language?",
				store: true,
				validate: (name) =>
					name?.trim().length > 0 && /^[\p{L}\s]+$/u.test(name) ? undefined : 'Specify a valid language name',
			},
			{
				type: 'select',
				name: 'language',
				message: "Select the translation you'd like to work with",
				options: this.languageChoices(),
				default: 'English',
				store: true,
			},
			{
				type: 'text',
				name: 'id',
				message: 'Specify the locale identifier (LCID)',
				default: (answers) => String(languages[answers.language].id),
				validate: (number) => {
					const parsed = Number.parseInt(number, 10);
					return Number.isInteger(parsed) && parsed > 0 ? undefined : 'Not a valid locale identifier (LCID)';
				},
			},
			{
				type: 'text',
				name: 'fontName',
				message: 'Specify the Font Name (non-Latin languages only)',
				default: (answers) => (languages[answers.language].font.name ? languages[answers.language].font.name : '-'),
			},
			{
				type: 'text',
				name: 'fontSize',
				message: 'Specify the Font Size (non-Latin languages only)',
				default: (answers) =>
					languages[answers.language].font.size ? String(languages[answers.language].font.size) : '-',
				validate: (number) => {
					if (number === '-') return undefined;
					const parsed = Number.parseInt(number, 10);
					return Number.isInteger(parsed) && parsed > 0 ? undefined : 'Not a valid font size';
				},
			},
			{
				type: 'text',
				name: 'codePage',
				message: 'Code page',
				default: (answers) =>
					languages[answers.language].code_page ? String(languages[answers.language].code_page) : '-',
				validate: (number) => {
					if (number === '-') return undefined;
					const parsed = Number.parseInt(number, 10);
					return Number.isInteger(parsed) && parsed > 0 ? undefined : 'Not a valid code page';
				},
			},
			{
				type: 'confirm',
				name: 'rtl',
				message: 'Is it a right-to-left (RTL) language?',
				default: (answers) => languages[answers.language].rtl === 'RTL',
			},
			{
				type: 'confirm',
				name: 'translateStrings',
				message: 'Do you want to continue and translate all strings?',
				default: true,
			},
			{
				name: 'Branding',
				message: 'Branding',
				default: (answers) => languages[answers.language].strings.Branding,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'SetupCaption',
				message: 'SetupCaption',
				default: (answers) => languages[answers.language].strings.SetupCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UninstallCaption',
				message: 'UninstallCaption',
				default: (answers) => languages[answers.language].strings.UninstallCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'LicenseSubCaption',
				message: 'LicenseSubCaption',
				default: (answers) => languages[answers.language].strings.LicenseSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ComponentsSubCaption',
				message: 'ComponentsSubCaption',
				default: (answers) => languages[answers.language].strings.ComponentsSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'DirSubCaption',
				message: 'DirSubCaption',
				default: (answers) => languages[answers.language].strings.DirSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'InstallingSubCaption',
				message: 'InstallingSubCaption',
				default: (answers) => languages[answers.language].strings.InstallingSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CompletedSubCaption',
				message: 'CompletedSubCaption',
				default: (answers) => languages[answers.language].strings.CompletedSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnComponentsSubCaption',
				message: 'UnComponentsSubCaption',
				default: (answers) => languages[answers.language].strings.UnComponentsSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnDirSubCaption',
				message: 'UnDirSubCaption',
				default: (answers) => languages[answers.language].strings.UnDirSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ConfirmSubCaption',
				message: 'ConfirmSubCaption',
				default: (answers) => languages[answers.language].strings.ConfirmSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UninstallingSubCaption',
				message: 'UninstallingSubCaption',
				default: (answers) => languages[answers.language].strings.UninstallingSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnCompletedSubCaption',
				message: 'UnCompletedSubCaption',
				default: (answers) => languages[answers.language].strings.UnCompletedSubCaption,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'BackBtn',
				message: 'BackBtn',
				default: (answers) => languages[answers.language].strings.BackBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'NextBtn',
				message: 'NextBtn',
				default: (answers) => languages[answers.language].strings.NextBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'AgreeBtn',
				message: 'AgreeBtn',
				default: (answers) => languages[answers.language].strings.AgreeBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'AcceptBtn',
				message: 'AcceptBtn',
				default: (answers) => languages[answers.language].strings.AcceptBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'DontAcceptBtn',
				message: 'DontAcceptBtn',
				default: (answers) => languages[answers.language].strings.DontAcceptBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'InstallBtn',
				message: 'InstallBtn',
				default: (answers) => languages[answers.language].strings.InstallBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UninstallBtn',
				message: 'UninstallBtn',
				default: (answers) => languages[answers.language].strings.UninstallBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CancelBtn',
				message: 'CancelBtn',
				default: (answers) => languages[answers.language].strings.CancelBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CloseBtn',
				message: 'CloseBtn',
				default: (answers) => languages[answers.language].strings.CloseBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'BrowseBtn',
				message: 'BrowseBtn',
				default: (answers) => languages[answers.language].strings.BrowseBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ShowDetailsBtn',
				message: 'ShowDetailsBtn',
				default: (answers) => languages[answers.language].strings.ShowDetailsBtn,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ClickNext',
				message: 'ClickNext',
				default: (answers) => languages[answers.language].strings.ClickNext,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ClickInstall',
				message: 'ClickInstall',
				default: (answers) => languages[answers.language].strings.ClickInstall,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ClickUninstall',
				message: 'ClickUninstall',
				default: (answers) => languages[answers.language].strings.ClickUninstall,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Name',
				message: 'Name',
				default: (answers) => languages[answers.language].strings.Name,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Completed',
				message: 'Completed',
				default: (answers) => languages[answers.language].strings.Completed,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'LicenseText',
				message: 'LicenseText',
				default: (answers) => languages[answers.language].strings.LicenseText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'LicenseTextCB',
				message: 'LicenseTextCB',
				default: (answers) => languages[answers.language].strings.LicenseTextCB,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'LicenseTextRB',
				message: 'LicenseTextRB',
				default: (answers) => languages[answers.language].strings.LicenseTextRB,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnLicenseText',
				message: 'UnLicenseText',
				default: (answers) => languages[answers.language].strings.UnLicenseText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnLicenseTextCB',
				message: 'UnLicenseTextCB',
				default: (answers) => languages[answers.language].strings.UnLicenseTextCB,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnLicenseTextRB',
				message: 'UnLicenseTextRB',
				default: (answers) => languages[answers.language].strings.UnLicenseTextRB,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Custom',
				message: 'Custom',
				default: (answers) => languages[answers.language].strings.Custom,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ComponentsText',
				message: 'ComponentsText',
				default: (answers) => languages[answers.language].strings.ComponentsText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ComponentsSubText1',
				message: 'ComponentsSubText1',
				default: (answers) => languages[answers.language].strings.ComponentsSubText1,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ComponentsSubText2_NoInstTypes',
				message: 'ComponentsSubText2_NoInstTypes',
				default: (answers) => languages[answers.language].strings.ComponentsSubText2_NoInstTypes,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ComponentsSubText2',
				message: 'ComponentsSubText2',
				default: (answers) => languages[answers.language].strings.ComponentsSubText2,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnComponentsText',
				message: 'UnComponentsText',
				default: (answers) => languages[answers.language].strings.UnComponentsText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnComponentsSubText1',
				message: 'UnComponentsSubText1',
				default: (answers) => languages[answers.language].strings.UnComponentsSubText1,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnComponentsSubText2_NoInstTypes',
				message: 'UnComponentsSubText2_NoInstTypes',
				default: (answers) => languages[answers.language].strings.UnComponentsSubText2_NoInstTypes,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnComponentsSubText2',
				message: 'UnComponentsSubText2',
				default: (answers) => languages[answers.language].strings.UnComponentsSubText2,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'DirText',
				message: 'DirText',
				default: (answers) => languages[answers.language].strings.DirText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'DirSubText',
				message: 'DirSubText',
				default: (answers) => languages[answers.language].strings.DirSubText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'DirBrowseText',
				message: 'DirBrowseText',
				default: (answers) => languages[answers.language].strings.DirBrowseText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnDirText',
				message: 'UnDirText',
				default: (answers) => languages[answers.language].strings.UnDirText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnDirSubText',
				message: 'UnDirSubText',
				default: (answers) => languages[answers.language].strings.UnDirSubText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UnDirBrowseText',
				message: 'UnDirBrowseText',
				default: (answers) => languages[answers.language].strings.UnDirBrowseText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'SpaceAvailable',
				message: 'SpaceAvailable',
				default: (answers) => languages[answers.language].strings.SpaceAvailable,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'SpaceRequired',
				message: 'SpaceRequired',
				default: (answers) => languages[answers.language].strings.SpaceRequired,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UninstallingText',
				message: 'UninstallingText',
				default: (answers) => languages[answers.language].strings.UninstallingText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'UninstallingSubText',
				message: 'UninstallingSubText',
				default: (answers) => languages[answers.language].strings.UninstallingSubText,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'FileError',
				message: 'FileError',
				default: (answers) => languages[answers.language].strings.FileError,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'FileError_NoIgnore',
				message: 'FileError_NoIgnore',
				default: (answers) => languages[answers.language].strings.FileError_NoIgnore,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CantWrite',
				message: 'CantWrite',
				default: (answers) => languages[answers.language].strings.CantWrite,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CopyFailed',
				message: 'CopyFailed',
				default: (answers) => languages[answers.language].strings.CopyFailed,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CopyTo',
				message: 'CopyTo',
				default: (answers) => languages[answers.language].strings.CopyTo,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Registering',
				message: 'Registering',
				default: (answers) => languages[answers.language].strings.Registering,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Unregistering',
				message: 'Unregistering',
				default: (answers) => languages[answers.language].strings.Unregistering,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'SymbolNotFound',
				message: 'SymbolNotFound',
				default: (answers) => languages[answers.language].strings.SymbolNotFound,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CouldNotLoad',
				message: 'CouldNotLoad',
				default: (answers) => languages[answers.language].strings.CouldNotLoad,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CreateFolder',
				message: 'CreateFolder',
				default: (answers) => languages[answers.language].strings.CreateFolder,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CreateShortcut',
				message: 'CreateShortcut',
				default: (answers) => languages[answers.language].strings.CreateShortcut,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CreatedUninstaller',
				message: 'CreatedUninstaller',
				default: (answers) => languages[answers.language].strings.CreatedUninstaller,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Delete',
				message: 'Delete',
				default: (answers) => languages[answers.language].strings.Delete,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'DeleteOnReboot',
				message: 'DeleteOnReboot',
				default: (answers) => languages[answers.language].strings.DeleteOnReboot,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ErrorCreatingShortcut',
				message: 'ErrorCreatingShortcut',
				default: (answers) => languages[answers.language].strings.ErrorCreatingShortcut,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ErrorCreating',
				message: 'ErrorCreating',
				default: (answers) => languages[answers.language].strings.ErrorCreating,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ErrorDecompressing',
				message: 'ErrorDecompressing',
				default: (answers) => languages[answers.language].strings.ErrorDecompressing,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ErrorRegistering',
				message: 'ErrorRegistering',
				default: (answers) => languages[answers.language].strings.ErrorRegistering,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ExecShell',
				message: 'ExecShell',
				default: (answers) => languages[answers.language].strings.ExecShell,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Exec',
				message: 'Exec',
				default: (answers) => languages[answers.language].strings.Exec,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Extract',
				message: 'Extract',
				default: (answers) => languages[answers.language].strings.Extract,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'ErrorWriting',
				message: 'ErrorWriting',
				default: (answers) => languages[answers.language].strings.ErrorWriting,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'InvalidOpcode',
				message: 'InvalidOpcode',
				default: (answers) => languages[answers.language].strings.InvalidOpcode,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'NoOLE',
				message: 'NoOLE',
				default: (answers) => languages[answers.language].strings.NoOLE,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'OutputFolder',
				message: 'OutputFolder',
				default: (answers) => languages[answers.language].strings.OutputFolder,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'RemoveFolder',
				message: 'RemoveFolder',
				default: (answers) => languages[answers.language].strings.RemoveFolder,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'RenameOnReboot',
				message: 'RenameOnReboot',
				default: (answers) => languages[answers.language].strings.RenameOnReboot,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Rename',
				message: 'Rename',
				default: (answers) => languages[answers.language].strings.Rename,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Skipped',
				message: 'Skipped',
				default: (answers) => languages[answers.language].strings.Skipped,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'CopyDetails',
				message: 'CopyDetails',
				default: (answers) => languages[answers.language].strings.CopyDetails,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'LogInstall',
				message: 'LogInstall',
				default: (answers) => languages[answers.language].strings.LogInstall,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Byte',
				message: 'Byte',
				default: (answers) => languages[answers.language].strings.Byte,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Kilo',
				message: 'Kilo',
				default: (answers) => languages[answers.language].strings.Kilo,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Mega',
				message: 'Mega',
				default: (answers) => languages[answers.language].strings.Mega,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
			{
				name: 'Giga',
				message: 'Giga',
				default: (answers) => languages[answers.language].strings.Giga,
				type: 'text',
				when: (answers) => answers.translateStrings,
				store: this.storeStrings,
			},
		]);

		this.answers = answers;
	}

	writing() {
		this.answers.name = pascalCase(this.answers.name);
		this.answers.rtl = this.answers.rtl ? 'RTL' : false;

		this.fs.copyTpl(
			this.templatePath('template.nlf.eta'),
			this.destinationPath(`${this.answers.name}.nlf`),
			this.answers,
		);
	}
}
